name: pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Code Linting
        run: |
          pip install poetry
          make lint
